// SPDX-License-Identifier: Apache-2.0
// Field-compatible subset of ONNX 1.19 onnx.proto.
// Source: https://github.com/onnx/onnx/blob/v1.19.0/onnx/onnx.proto
syntax = "proto2";
package jogonnx;
option optimize_for = LITE_RUNTIME;

message StringStringEntryProto {
  optional string key = 1;
  optional string value = 2;
}

message TensorShapeProto {
  message Dimension {
    oneof value {
      int64 dim_value = 1;
      string dim_param = 2;
    }
  }
  repeated Dimension dim = 1;
}

message TypeProto {
  message Tensor {
    optional int32 elem_type = 1;
    optional TensorShapeProto shape = 2;
  }
  oneof value {
    Tensor tensor_type = 1;
  }
}

message ValueInfoProto {
  optional string name = 1;
  optional TypeProto type = 2;
}

message TensorProto {
  message Segment {
    optional int64 begin = 1;
    optional int64 end = 2;
  }
  repeated int64 dims = 1;
  optional int32 data_type = 2;
  optional Segment segment = 3;
  repeated float float_data = 4 [packed = true];
  repeated int32 int32_data = 5 [packed = true];
  repeated bytes string_data = 6;
  repeated int64 int64_data = 7 [packed = true];
  optional string name = 8;
  optional bytes raw_data = 9;
  repeated double double_data = 10 [packed = true];
  repeated uint64 uint64_data = 11 [packed = true];
  repeated StringStringEntryProto external_data = 13;
  optional int32 data_location = 14;
}

message SparseTensorProto {}

message AttributeProto {
  enum AttributeType {
    UNDEFINED = 0;
    FLOAT = 1;
    INT = 2;
    STRING = 3;
    TENSOR = 4;
    GRAPH = 5;
    FLOATS = 6;
    INTS = 7;
    STRINGS = 8;
    TENSORS = 9;
    GRAPHS = 10;
  }
  optional string name = 1;
  optional float f = 2;
  optional int64 i = 3;
  optional bytes s = 4;
  optional TensorProto t = 5;
  optional GraphProto g = 6;
  repeated float floats = 7 [packed = true];
  repeated int64 ints = 8 [packed = true];
  repeated bytes strings = 9;
  repeated TensorProto tensors = 10;
  repeated GraphProto graphs = 11;
  optional AttributeType type = 20;
}

message NodeProto {
  repeated string input = 1;
  repeated string output = 2;
  optional string name = 3;
  optional string op_type = 4;
  repeated AttributeProto attribute = 5;
  optional string domain = 7;
}

message GraphProto {
  repeated NodeProto node = 1;
  optional string name = 2;
  repeated TensorProto initializer = 5;
  repeated SparseTensorProto sparse_initializer = 15;
  repeated ValueInfoProto input = 11;
  repeated ValueInfoProto output = 12;
  repeated ValueInfoProto value_info = 13;
}

message OperatorSetIdProto {
  optional string domain = 1;
  optional int64 version = 2;
}

message ModelProto {
  optional int64 ir_version = 1;
  optional string producer_name = 2;
  repeated OperatorSetIdProto opset_import = 8;
  optional GraphProto graph = 7;
}
