#!/usr/bin/env python3
"""Render one matched operator sweep as a native LaTeX speedup table."""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from pathlib import Path
from typing import Any


def fail(message: str) -> None:
    raise SystemExit(f"render_operator_table: {message}")


def document(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        fail(f"cannot read {path}: {error}")
    if not isinstance(value, dict):
        fail(f"expected an object in {path}")
    return value


def median_times(path: Path) -> dict[str, float]:
    try:
        with path.open(newline="", encoding="utf-8") as stream:
            rows = list(csv.DictReader(stream))
    except OSError as error:
        fail(f"cannot read {path}: {error}")
    groups: dict[str, list[float]] = {}
    for row in rows:
        try:
            value = float(row["seconds"])
            system = row["system"]
        except (KeyError, ValueError):
            fail(f"invalid timing row in {path}")
        if not math.isfinite(value) or value <= 0:
            fail(f"invalid latency in {path}")
        groups.setdefault(system, []).append(value)
    return {name: statistics.median(values) for name, values in groups.items()}


def shade(value: float) -> str:
    if value < 0.5:
        return "speedslow"
    if value < 0.9:
        return "speedbehind"
    if value <= 1.1:
        return "speedparity"
    return "speedahead"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixtures", type=Path, required=True)
    parser.add_argument("--runs-root", type=Path, required=True)
    parser.add_argument("--baseline", default="onnxruntime")
    parser.add_argument("--candidate", default="joggle")
    parser.add_argument("--baseline-label", default="ONNX Runtime")
    parser.add_argument("--row-label", default="MatMul")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--summary", type=Path, required=True)
    args = parser.parse_args()

    fixture_doc = document(args.fixtures)
    cases = fixture_doc.get("cases")
    if not isinstance(cases, list) or not cases:
        fail("fixture manifest has no cases")

    values: list[dict[str, Any]] = []
    revisions: set[str] = set()
    hosts: set[tuple[str, str]] = set()
    for case in cases:
        if not isinstance(case, dict) or not isinstance(case.get("case"), str):
            fail("fixture manifest contains an invalid case")
        name = case["case"]
        shape = case.get("shape")
        if not isinstance(shape, dict) or any(key not in shape for key in "MKN"):
            fail(f"{name} has no M/K/N shape")
        directory = args.runs_root / name
        record = document(directory / "record.json")
        if record.get("repo_dirty") is not False:
            fail(f"{name} was measured from a dirty repository")
        revision = record.get("repo_revision")
        host = record.get("host")
        if not isinstance(revision, str) or not isinstance(host, dict):
            fail(f"{name} has incomplete provenance")
        revisions.add(revision)
        hosts.add((str(host.get("node")), str(host.get("platform"))))
        medians = median_times(directory / "runs.csv")
        if args.baseline not in medians or args.candidate not in medians:
            fail(f"{name} does not contain both requested systems")
        speedup = medians[args.baseline] / medians[args.candidate]
        values.append({
            "case": name,
            "M": int(shape["M"]),
            "K": int(shape["K"]),
            "N": int(shape["N"]),
            "baseline_seconds": medians[args.baseline],
            "candidate_seconds": medians[args.candidate],
            "speedup": speedup,
        })
    if len(revisions) != 1 or len(hosts) != 1:
        fail("all cells must share one clean revision and host")

    geomean = math.exp(statistics.fmean(math.log(row["speedup"]) for row in values))
    column_spec = "l" + "r" * (len(values) + 1)
    headers = " & ".join(
        rf"\rotatebox{{90}}{{${row['M']}\!\times\!{row['K']}\!\times\!{row['N']}$}}"
        for row in values
    )
    cells = " & ".join(
        rf"\cellcolor{{{shade(row['speedup'])}}}{row['speedup']:.2f}"
        for row in values
    )
    revision = next(iter(revisions))[:12]
    latex = rf"""% Generated by paper/render_operator_table.py; do not edit.
\definecolor{{speedslow}}{{HTML}}{{F4D7D7}}
\definecolor{{speedbehind}}{{HTML}}{{F7E8C6}}
\definecolor{{speedparity}}{{HTML}}{{E2E8F0}}
\definecolor{{speedahead}}{{HTML}}{{C8E6D2}}
\begin{{table*}}[t]
  \centering
  \setlength{{\tabcolsep}}{{1.7pt}}
  \renewcommand{{\arraystretch}}{{1.04}}
  \resizebox{{\textwidth}}{{!}}{{%
  \begin{{tabular}}{{{column_spec}}}
    \toprule
    Benchmark & {headers} & Geomean \\
    \midrule
    \multicolumn{{{len(values) + 2}}}{{l}}{{\textit{{vs {args.baseline_label}}}}} \\
    {args.row_label} & {cells} & \cellcolor{{{shade(geomean)}}}{geomean:.2f} \\
    \bottomrule
  \end{{tabular}}}}
  \caption{{Matched single-thread speedup of {args.row_label} generated by Joggle
  over {args.baseline_label} (baseline median/Joggle median; higher is better).
  Every cell uses the same metric and validated output. Diagnostic host,
  4 outer trials per system, 100 timed invocations per trial, revision
  \texttt{{{revision}}}. These development-host data are not submission results.}}
  \label{{tab:operator-sweep-diagnostic}}
\end{{table*}}
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(latex, encoding="utf-8")
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    with args.summary.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(values[0]))
        writer.writeheader()
        writer.writerows(values)


if __name__ == "__main__":
    main()
